name: Casino
version: ${project.version}
main: eu.mikroskeem.mod.casino.Casino
authors:
- gyuriX
- mikroskeem
description: Casino plugin, rewritten to work without SpigotLib

depend:
- Vault
- ProtocolLib

commands:
  casino:
    permission: casino.reload

permissions:
  casino.use:
    default: true

  casino.reload:
    default: op

  casino.createsign:
    default: op