name: Casino
version: ${project.version}
main: eu.mikroskeem.mod.casino.Casino
authors:
- gyuriX
- mikroskeem
description: Casino plugin, rewritten to work without SpigotLib

depend:
- Vault

commands:
  casino:
    permission: casino.use

permissions:
  casino.use:
    default: op